---
# SPDX-License-Identifier: MIT-0
# CI scenario: Simulates GitHub Actions environment
# Purpose: Reproduce CI failures locally before pushing

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: podman

platforms:
  - name: fedora-ci
    image: registry.fedoraproject.org/fedora:latest
    # Use pre-built image
    pre_build_image: true
    # Keep container running with sleep infinity
    command: sleep infinity
    # Environment variables
    env:
      CI: "true"
    # Pull latest image
    pull: true

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      roles_path: /home/parinya/personal/ansible-config/roles
  inventory:
    group_vars:
      all:
        # These MUST match ci.yml settings exactly
        common_enable_rpm_fusion: false
        common_install_nvidia_drivers: false
        common_configure_custom_dns: false
        common_install_d2: false
        locale_install_gui_tools: false

# CI-optimized test sequence (focus on idempotence)
scenario:
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
  enabled: true
