---
- name: Ensure Wi-Fi is never blocked on all hosts
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Check rfkill status
      command: rfkill list
      register: rfkill_status
      changed_when: false
      failed_when: false

    - name: Show rfkill status (debug)
      debug:
        msg: "{{ rfkill_status.stdout }}"

    - name: Unblock all rfkill devices
      command: rfkill unblock all
      when: "'Soft blocked: yes' in rfkill_status.stdout"

    - name: Ensure NetworkManager Wi-Fi is enabled
      command: nmcli radio wifi on
      changed_when: false
      failed_when: false

    - name: Ensure NetworkManager is running
      systemd:
        name: NetworkManager
        state: started
        enabled: true

    # ---------- Vendor-specific protection (safe) ----------
    - name: Detect acer_wmi module
      command: lsmod
      register: lsmod_out
      changed_when: false
      failed_when: false

    - name: Disable acer_wmi to prevent Wi-Fi soft block (Acer only)
      copy:
        dest: /etc/modprobe.d/acer-wmi.conf
        content: |
          blacklist acer_wmi
      when: "'acer_wmi' in lsmod_out.stdout"
      notify: reboot_if_needed

    # ---------- Persistent Wi-Fi enable ----------
    - name: Force Wi-Fi enabled at boot via NetworkManager config
      copy:
        dest: /etc/NetworkManager/conf.d/10-wifi-always-on.conf
        content: |
          [device]
          wifi.scan-rand-mac-address=no

          [connection]
          wifi.powersave=2

      notify: restart_nm

  handlers:
    - name: restart_nm
      systemd:
        name: NetworkManager
        state: restarted

    - name: reboot_if_needed
      reboot:
        msg: "Rebooting to apply Wi-Fi unblock policy"
        reboot_timeout: 600