---
- name: Ensure Wi-Fi is never blocked on all hosts
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Check rfkill status
      ansible.builtin.command: rfkill list
      register: rfkill_status
      changed_when: false
      failed_when: false

    - name: Show rfkill status (debug)
      ansible.builtin.debug:
        msg: "{{ rfkill_status.stdout }}"

    - name: Unblock all rfkill devices
      ansible.builtin.command: rfkill unblock all
      register: rfkill_unblock
      changed_when: rfkill_unblock.rc == 0
      when: "'Soft blocked: yes' in rfkill_status.stdout"

    - name: Ensure NetworkManager Wi-Fi is enabled
      ansible.builtin.command: nmcli radio wifi on
      changed_when: false
      failed_when: false

    - name: Ensure NetworkManager is running
      ansible.builtin.systemd:
        name: NetworkManager
        state: started
        enabled: true

    # ---------- Vendor-specific protection (safe) ----------
    - name: Detect acer_wmi module
      ansible.builtin.command: lsmod
      register: lsmod_out
      changed_when: false
      failed_when: false

    - name: Disable acer_wmi to prevent Wi-Fi soft block (Acer only)
      ansible.builtin.copy:
        dest: /etc/modprobe.d/acer-wmi.conf
        content: |
          blacklist acer_wmi
        mode: '0644'
      when: "'acer_wmi' in lsmod_out.stdout"
      notify: Reboot_if_needed

    # ---------- Persistent Wi-Fi enable ----------
    - name: Force Wi-Fi enabled at boot via NetworkManager config
      ansible.builtin.copy:
        dest: /etc/NetworkManager/conf.d/10-wifi-always-on.conf
        content: |
          [device]
          wifi.scan-rand-mac-address=no

          [connection]
          wifi.powersave=2
        mode: '0644'

      notify: Restart_nm

  handlers:
    - name: Restart_nm
      ansible.builtin.systemd:
        name: NetworkManager
        state: restarted

    - name: Reboot_if_needed
      ansible.builtin.reboot:
        msg: "Rebooting to apply Wi-Fi unblock policy"
        reboot_timeout: 600
