---
# SPDX-License-Identifier: MIT-0
# Molecule collection requirements for testing

collections:
  # Container management for Fedora testing
  - name: containers.podman
    version: ">=1.10.0"

  # Additional collections for testing
  - name: community.general
    version: ">=8.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
