---
# SPDX-License-Identifier: MIT-0
# Default scenario: Local Podman testing
# Purpose: Fast local development iteration

dependency:
  name: galaxy
  options:
    requirements-file: molecule/requirements.yml

driver:
  name: podman

platforms:
  - name: fedora-latest
    image: registry.fedoraproject.org/fedora:latest
    # Use pre-built image
    pre_build_image: true
    # Keep container running with sleep infinity
    command: sleep infinity
    # Environment variables
    env:
      CI: "true"
    # Pull latest image
    pull: true

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      roles_path: /home/parinya/personal/ansible-config/roles
  inventory:
    group_vars:
      all:
        # CI-safe defaults for testing
        common_enable_rpm_fusion: false
        common_install_nvidia_drivers: false
        common_configure_custom_dns: false
        common_install_d2: false
        locale_install_gui_tools: false
        # Skip preflight checks in containers
        common_skip_disk_check: true
        common_skip_preflight: true

# Test sequence for local development
scenario:
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
  enabled: true
