---
# SPDX-License-Identifier: MIT-0
# Firmware update tasks

- name: Check network connectivity for firmware updates
  ansible.builtin.uri:
    url: https://cdn.fwupd.org
    timeout: 10
    status_code: 200
  register: common_firmware_network_check
  ignore_errors: true
  changed_when: false
  when:
    - common_install_firmware_updates | bool
    - lookup('env', 'CI') != 'true'
  tags:
    - firmware

- name: Refresh firmware metadata
  ansible.builtin.command: fwupdmgr refresh --force
  register: common_fwupdmgr_refresh
  changed_when: false
  when:
    - common_install_firmware_updates | bool
    - lookup('env', 'CI') != 'true'
    - common_firmware_network_check is succeeded
  become: true
  tags:
    - firmware

- name: Get available firmware updates
  ansible.builtin.command: fwupdmgr get-updates
  register: common_firmware_updates
  changed_when: false
  failed_when: common_firmware_updates.rc not in [0, 2]
  when:
    - common_install_firmware_updates | bool
    - lookup('env', 'CI') != 'true'
    - common_firmware_network_check is succeeded
  tags:
    - firmware

- name: Update firmware
  ansible.builtin.command: fwupdmgr update -y
  register: common_fwupdmgr_update
  changed_when: false
  when:
    - common_install_firmware_updates | bool
    - common_firmware_updates.stdout | default('') | length > 0
    - lookup('env', 'CI') != 'true'
    - common_firmware_network_check is succeeded
  become: true
  tags:
    - firmware
