---
# SPDX-License-Identifier: MIT-0
# =============================================================================
# power role - TLP power management for Fedora Workstations
# =============================================================================

- name: Fail if power_install_tlp is not set
  ansible.builtin.fail:
    msg: "power_install_tlp must be set to true or false"
  when: power_install_tlp is not defined

- name: Import tlp_install.yml
  ansible.builtin.import_tasks: tlp_install.yml
  when: power_install_tlp | bool
